const fruits_vegetables = [
    "alma",
    "áfonya",
    "avokádó",
    "borsó",
    "brokkoli",
    "cékla",
    "cseresznye",
    "dinnye",
    "eper",
    "füge",
    "gomba",
    "grapefruit",
    "káposzta",
    "kivi",
    "körte",
    "krumpli",
    "lencse",
    "mango",
    "málna",
    "maracuja",
    "mogyoró",
    "nektarin",
    "narancs",
    "paprika",
    "paradicsom",
    "sárgadinnye",
    "sárgarépa",
    "szilva",
    "tök",
    "uborka",
    "zöldbab",
    "zeller",
    "zöldalma",
    "zöldpaprika",
    "zöldborsó",
    "cukkini",
    "kelkáposzta",
    "sóska"
]

const it_words = [
    "Adat",
    "Adatbázis",
    "Alkalmazás",
    "Alkalmazásfejlesztés",
    "Algoritmus",
    "Automatikus",
    "Biztonság",
    "Böngésző",
    "Cloud",
    "Datacenter",
    "Digitális",
    "DNS",
    "E-mail",
    "Felhasználó",
    "Folyamat",
    "Hardver",
    "Hibakeresés",
    "Információ",
    "Internet",
    "Kód",
    "Kódolás",
    "Kommunikáció",
    "Korreláció",
    "Licenc",
    "Mobil",
    "Program",
    "Programozás",
    "Rendszer",
    "Rendszergazda",
    "Szoftver",
    "Tűzfal",
    "Titkosítás",
    "Töltés",
    "Törlés",
    "Üzenet",
    "Weboldal",
    "Webtárhely",
    "WiFi",
    "MySQL",
    "Zárolás",
    "Zsarolóvírus",
    "Zöldmezős",
    "Cikk",
    "Szekrény",
    "Klónozás",
    "Protokoll",
    "Feltörés",
    "Virtualizáció",
    "Futtatás"
]

const animals = [
    "kutya",
    "macska",
    "ló",
    "tigris",
    "medve",
    "elefánt",
    "zebra",
    "oroszlán",
    "nyúl",
    "farkas",
    "majom",
    "gólya",
    "kígyó",
    "róka",
    "bálna",
    "sas",
    "pingvin",
    "hal",
    "csiga",
    "bagoly",
    "kacsa",
    "béka",
    "pók",
    "pillangó",
    "méhecske",
    "szamár",
    "tehén",
    "csirke",
    "szarvas",
    "rák",
    "varjú",
    "galamb",
    "disznó",
    "fóka",
    "őz",
    "liba",
    "kenguru",
    "mosómedve",
    "sün",
    "hiéna"
]

const food = [
    "kenyér",
    "vaj",
    "tészta",
    "rizs",
    "hús",
    "hal",
    "tojás",
    "főzelék",
    "leves",
    "saláta",
    "sütemény",
    "csokoládé",
    "joghurt",
    "tej",
    "sajt",
    "fagyi",
    "pizza",
    "hamburger",
    "hotdog",
    "tortilla",
    "pasta",
    "müzli",
    "szendvics",
    "fánk",
    "gulyás",
    "pörkölt",
    "tál",
    "falafel",
    "pannacotta",
    "tortellini",
    "tökfőzelék",
    "piskóta",
    "szendvics",
    "lazac"
]

const nature = [
    "erdő",
    "hegy",
    "tó",
    "folyó",
    "patak",
    "tenger",
    "szél",
    "eső",
    "nap",
    "hold",
    "csillag",
    "felhő",
    "virág",
    "fű",
    "fa",
    "szikla",
    "mocsár",
    "homok",
    "barlang",
    "láp",
    "fűszál",
    "növény",
    "gyökér",
    "ág",
    "gyümölcs",
    "termés",
    "talaj",
    "széna",
    "zöld",
    "bárányfelhő",
    "párás",
    "napfény",
    "reggel",
    "naplemente",
    "szivárvány",
    "tavasz",
    "ősz"
];

const sports = [
    "kosárlabda",
    "Futball",
    "Röplabda",
    "Tenisz",
    "Asztalitenisz",
    "Tollaslabda",
    "Atlétika",
    "Úszás",
    "Kézilabda",
    "Vízilabda",
    "Birkózás",
    "Judo",
    "Boksz",
    "Íjászat",
    "Fallabda",
    "Rögbi",
    "Hoki",
    "Krikett",
    "Baseball",
    "Golf",
    "Síelés",
    "Snowboardozás",
    "Jégkorcsolyázás",
    "Gördeszkázás",
    "Karate",
    "Taekwondo",
    "Evezés",
    "Kenuzás",
    "Szörfözés",
    "Triatlon",
    "Maratonfutás",
    "Sziklamászás",
    "Lovaglás",
    "Sakkozás",
    "Sárkányhajózás",
    "BMX",
    "Torna",
    "Erőemelés",
    "Súlyemelés",
    "Kerékpározás"
];

const countries = [
    "Izland",
    "Norvégia",
    "Svédország",
    "Finnország",
    "Dánia",
    "Németország",
    "Franciaország",
    "Olaszország",
    "Spanyolország",
    "Portugália",
    "Belgium",
    "Hollandia",
    "Svájc",
    "Görögország",
    "Lengyelország",
    "Csehország",
    "Szlovákia",
    "Ausztria",
    "Magyarország",
    "Horvátország",
    "Szerbia",
    "Bulgária",
    "Románia",
    "Ukrajna",
    "Oroszország",
    "Kanada",
    "Egyesült Államok",
    "Mexikó",
    "Argentína",
    "Brazília",
    "Chile",
    "Kolumbia",
    "Ausztrália",
    "Új-Zéland",
    "Kína",
    "Japán",
    "India",
    "Thaiföld",
    "Vietnam",
    "Dél-Korea",
    "Törökország"
];

const boardGame = [
    "tábla",
    "bábu",
    "kocka",
    "kártya",
    "szabályzat",
    "kör",
    "dobás",
    "lépés",
    "pontszám",
    "figura",
    "stratégia",
    "taktika",
    "szövetség",
    "verseny",
    "csapatjáték",
    "egyéni játék",
    "kihívás",
    "kártyapakli",
    "mező",
    "cél",
    "jutalom",
    "büntetés",
    "várakozási idő",
    "kör vége",
    "győzelem",
    "vereség",
    "start",
    "célvonal",
    "időlimit",
    "küldetés",
    "szerepjáték",
    "logika",
    "ügyesség",
    "kooperáció",
    "interakció",
    "forduló",
    "küzdelem",
    "erőforrás",
    "megszerzés",
    "kihívás kártya"
];

const famous = [
    "Michael Jackson",
    "Madonna",
    "Elvis Presley",
    "Whitney Houston",
    "Freddie Mercury",
    "Beyoncé",
    "Taylor Swift",
    "Ed Sheeran",
    "Drake",
    "Adele",
    "Prince",
    "Lady Gaga",
    "Billie Eilish",
    "Stevie Wonder",
    "Bruno Mars",
    "David Bowie",
    "Elton John",
    "Bob Dylan",
    "Rihanna",
    "Justin Bieber",
    "Bob Marley",
    "Shakira",
    "Pink Floyd",
    "AC/DC",
    "Nirvana",
    "The Beatles",
    "Queen",
    "Linkin Park",
    "Metallica",
    "Coldplay",
    "Red Hot Chili Peppers",
    "Fleetwood Mac",
    "Jay-Z",
    "Katy Perry"
]